source ‘https://github.com/CocoaPods/Specs.git‘
platform :ios, ‘9.3’

target 'PhotoViewerWhithAlamofire' do

  use_frameworks!

 pod 'Alamofire', '~> 4.3'
 pod 'AlamofireObjectMapper', '~> 4.0'
 pod 'SlideMenuControllerSwift', '~> 3.0'

end
