source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!


target 'PhotoViewerWhithAlamofire' do
 pod 'Alamofire', '~> 3.3'
 pod 'AlamofireObjectMapper', '~> 3.0'
 pod 'ObjectMapper', '~> 1.2'
 pod 'SlideMenuControllerSwift'
end